import type { Booking } from './api';

/**
 * TEMPORARY sample data for previewing the My Bookings screen while the bookings API is not
 * wired up. Dates are relative to today so every tab always has something in it.
 * Delete this file (and the USE_MOCK_BOOKINGS switch in api.ts) once real data loads.
 */
const dayFromToday = (days: number, hour = 0) => {
    const d = new Date();
    d.setDate(d.getDate() + days);
    d.setHours(hour, 0, 0, 0);
    const pad = (n: number) => String(n).padStart(2, '0');
    return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:00:00`;
};

export const MOCK_BOOKINGS: Booking[] = [
    {
        bookingId: 'MFB-1760100000000-A3F2',
        bookingDate: dayFromToday(5),
        experienceId: 101,
        experienceName: 'Candlelight Rooftop Dinner',
        experienceSlug: 'candlelight-rooftop-dinner',
        locationName: 'Mumbai',
        timeSlotLabel: 'Evening',
        startTime: '19:00',
        endTime: '22:00',
        guestCount: 2,
        status: 'CONFIRMED',
        resolvedPricePerPerson: 4999,
        totalAmount: 9998,
        addonsTotal: 1499,
        grandTotal: 11497,
        pincode: '400050',
        confirmedAt: dayFromToday(-2, 14),
        createdAt: dayFromToday(-2, 13),
        addons: [
            { id: 1, addonName: 'Rose petal pathway', effectivePrice: 999 },
            { id: 2, addonName: 'Personalised cake (1 kg)', effectivePrice: 500 },
            { id: 3, addonName: 'Welcome mocktails', effectivePrice: 0, free: true },
        ],
    },
    {
        bookingId: 'MFB-1760200000000-B7C1',
        bookingDate: dayFromToday(12),
        experienceId: 102,
        experienceName: 'Surprise Birthday Room Decor',
        experienceSlug: 'surprise-birthday-room-decor',
        locationName: 'Pune',
        timeSlotLabel: 'Afternoon',
        startTime: '14:00',
        endTime: '17:00',
        guestCount: 1,
        status: 'PENDING',
        resolvedPricePerPerson: 3499,
        totalAmount: 3499,
        addonsTotal: 0,
        grandTotal: 3499,
        pincode: '411001',
        createdAt: dayFromToday(-1, 10),
        addons: [],
    },
    {
        bookingId: 'MFB-1758000000000-C9D4',
        bookingDate: dayFromToday(-20),
        experienceId: 103,
        experienceName: 'Anniversary Cabana by the Pool',
        experienceSlug: 'anniversary-cabana-by-the-pool',
        locationName: 'Goa',
        timeSlotLabel: 'Sunset',
        startTime: '17:30',
        endTime: '20:30',
        guestCount: 2,
        status: 'CONFIRMED',
        resolvedPricePerPerson: 6499,
        totalAmount: 12998,
        addonsTotal: 2499,
        grandTotal: 15497,
        pincode: '403516',
        confirmedAt: dayFromToday(-35, 11),
        createdAt: dayFromToday(-35, 10),
        addons: [{ id: 4, addonName: 'Live acoustic guitarist', effectivePrice: 2499 }],
    },
    {
        bookingId: 'MFB-1757000000000-D2E8',
        bookingDate: dayFromToday(-45),
        experienceId: 104,
        experienceName: 'Proposal Setup with Fairy Lights',
        experienceSlug: 'proposal-setup-with-fairy-lights',
        locationName: 'Bengaluru',
        timeSlotLabel: 'Night',
        startTime: '20:00',
        endTime: '23:00',
        guestCount: 2,
        status: 'PENDING',
        resolvedPricePerPerson: 5499,
        totalAmount: 10998,
        addonsTotal: 0,
        grandTotal: 10998,
        pincode: '560038',
        createdAt: dayFromToday(-50, 18),
        addons: [],
    },
    {
        bookingId: 'MFB-1759000000000-E5F3',
        bookingDate: dayFromToday(8),
        experienceId: 105,
        experienceName: 'Baby Shower Balloon Arch',
        experienceSlug: 'baby-shower-balloon-arch',
        locationName: 'Delhi',
        timeSlotLabel: 'Morning',
        startTime: '10:00',
        endTime: '13:00',
        guestCount: 15,
        status: 'CANCELLED',
        resolvedPricePerPerson: 399,
        totalAmount: 5985,
        addonsTotal: 799,
        grandTotal: 6784,
        pincode: '110017',
        createdAt: dayFromToday(-6, 9),
        addons: [{ id: 5, addonName: 'Photo booth props', effectivePrice: 799 }],
    },
    {
        bookingId: 'MFB-1759500000000-F1A6',
        bookingDate: dayFromToday(3),
        experienceId: 106,
        experienceName: 'Private Movie Night for Two',
        experienceSlug: 'private-movie-night-for-two',
        locationName: 'Hyderabad',
        timeSlotLabel: 'Late evening',
        startTime: '21:00',
        endTime: '00:00',
        guestCount: 2,
        status: 'FAILED',
        resolvedPricePerPerson: 2999,
        totalAmount: 5998,
        addonsTotal: 0,
        grandTotal: 5998,
        pincode: '500033',
        failureReason: 'The selected time slot was fully booked by the time payment started.',
        createdAt: dayFromToday(-1, 20),
        addons: [],
    },
];
